<template>
  <div>
    <highcharts :options="chartOptions"></highcharts>
  </div>
</template>

<script>
export default {
  name: "HelloWorld",
  data() {
    return {
      chartOptions: {
        chart: {
          zoomType: "xy",
          type: 'spline'
        },
        title: {
          text: "Distribution of lifetime revenue (LTR) & Customer",
          style: { "font-family": "Gill sans", "font-size": "26px" }
        },
        xAxis: [
          {
            crosshair: false,
          },
        ],
        yAxis: [
          {
            // Primary yAxis
            labels: {
              // format: "{value}°C",
            },
            // title: {
            // 	text: "Temperature",
            // },
          },
          {
            // Secondary yAxis
            // title: {
            // 	text: "Rainfall",
            // },
            labels: {
              format: "{value} mm",
            },
            opposite: true,
          },
        ],
        tooltip: {
          shared: true,
        },
        series: [
          {
            name: "",
            type: "spline",
            yAxis: 1,
            color: '#7878EC',
            data: [
              2.3,
              10.7,
              20.4,
              28.8,
              37.5,
              43.7,
              48.2,
              51.1,
              53.7,
              57,
              61.8,
              65,
              67.6,
              69.9,
              72.5,
              73.8,
              74.1,
              77.3,
              79.9,
              81.9,
              83.8,
              84.8,
              85.1,
              85.8,
              86.4,
              86.7,
              88,
              89,
              90,
              90.9,
              91.3,
              91.9,
              92.2,
              92.9,
              93.9,
              94.2,
              94.8,
              95.5,
              95.8,
              95.8,
              96.1,
              96.1,
              96.1,
              96.4,
              96.8,
              97.7,
              97.7,
              98.1,
              98.1,
              98.1,
              98.4,
              98.4,
              98.4,
              98.4,
              98.4,
              98.4,
              98.4,
              98.4,
              98.4,
              98.4,
              98.4,
              98.4,
              98.7,
              98.7,
              98.7,
              98.7,
              98.7,
              98.7,
              98.7,
              99,
              99,
              99,
              99.4,
              99.4,
              99.4,
              99.4,
              99.4,
              99.4,
              99.7,
              99.7,
              99.7,
              99.7,
              100,
            ],
            tooltip: {
              valueSuffix: " mm",
            },
          },
          {
            name: "",
            type: "area",
            color: '#7878EC',
            data: [
              7,
              26,
              30,
              26,
              27,
              19,
              14,
              9,
              8,
              10,
              15,
              10,
              8,
              7,
              8,
              4,
              1,
              10,
              8,
              6,
              6,
              3,
              1,
              2,
              2,
              1,
              4,
              3,
              3,
              3,
              1,
              2,
              1,
              2,
              3,
              1,
              2,
              2,
              1,
              0,
              1,
              0,
              0,
              1,
              1,
              3,
              0,
              1,
              0,
              0,
              1,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              1,
              0,
              0,
              0,
              0,
              0,
              0,
              1,
              0,
              0,
              1,
              0,
              0,
              0,
              0,
              0,
              1,
              0,
              0,
              0,
              1,
            ],
            tooltip: {
              valueSuffix: "°C",
            },
          },
        ],
      },
    };
  },
  mounted() { },
  methods: {
    myCallback() {
      console.log("this is callback function");
    },
  },
};
</script>

<style>
.highcharts-container {
	width: 600px;
	height: 520px;
	border: 1px solid #ddd;
	margin: auto;
}
</style>
